title: Jaselle Brower # your name (or website title) here
logo: "/images/FC58673C-E6A3-4124-871C-F0577B2AA70A.jpeg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  GIS Analyst at ADB Companies, LLC.
  <br><br>
  Current Graduate Student at the University of Oklahoma, M.S. Geospatial Technologies
  <br><br>
  Graduated from the University of Texas at San Antonio, B.A. Geography, Summa Cum Laude 
  <br><br>
  <a href="https://www.linkedin.com/in/jaselle-brower-12b14115b">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
